extern  SHORT               big_mousex;
extern  SHORT               big_mousey;
extern  SHORT               mouse_limit;
extern  LONG                sprite_list[];
extern  LONG                copper_list[];
extern  LONG                a_sprite[];
extern  SHORT               mmousex;
extern  SHORT               mmousey;
extern  LONG                spare_cl;
extern  LONG                screen_origin;
extern  LONG                *p_addr;
extern  SHORT               pal;
extern  SHORT               sprites_in;
extern  struct  s_serial    serial;
extern  SHORT               cheat;
extern  volatile LONG       vbi_timer;
extern  SHORT               bring_up_two;
extern  USHORT              land_checksum;
extern  SHORT               funny_done;
//extern  LONG                sprite_data;
//extern  LONG                sprite_data_32;
extern  LONG                score;
extern  USHORT              use_modem;
extern  USHORT               quick_io;
extern  UBYTE               sound_effect;
extern  UBYTE               login[];
extern  SHORT               saved;
extern  UBYTE               filename[];
extern  UBYTE               drawer[];
extern  SHORT               dump_screen_number;
extern  SHORT               all_of_city;
extern  SHORT               war;
extern  SHORT               tcmap[];
extern  SHORT               level_number;
extern  LONG                screen_pointer[];
extern  SHORT               tempo;
extern  SHORT               tempo_now;
extern  SHORT               music_now;
extern  SHORT               music;
extern  SHORT               music_off;
extern  SHORT               effect_off;
extern  SHORT               effect;
extern  SHORT               beat_two;
extern  SHORT               battle_won[];
extern  SHORT               start_of_game;
extern  SHORT               sound_in;
extern  SHORT               old_view_who;
extern  SHORT               view_timer;
extern  UBYTE               message[];
extern  SHORT               a_flat_block;
extern  LONG                back_scr;
extern  LONG                w_screen;
extern  LONG                d_screen;
extern  /*volatile*/ SHORT      shift;
extern  /*volatile*/ UBYTE      inkey;
extern  /*volatile*/ UBYTE      asckey;
extern  USHORT              game_turn;
extern  volatile SHORT      left_button;
extern  struct  m_magnet    magnet[];
extern  SHORT               alt[];
extern  UBYTE               map_who[];
extern  UBYTE               map_alt[];
extern  UBYTE               map_bk2[];
extern  UBYTE               map_blk[];
extern	UBYTE				title_map_blk[300];
extern  USHORT              map_steps[];
extern  struct  p_peeps     peeps[];
extern  volatile SHORT      mousex;
extern  volatile SHORT      mousey;
extern  SHORT               no_peeps;
extern  SHORT               player;
extern  volatile SHORT      right_button;
extern  USHORT              seed;
extern  USHORT              start_seed;
extern  SHORT               serial_off;
extern  SHORT               toggle;
extern  LONG                work_screen;
extern  SHORT               xmax;
extern  SHORT               xmin;
extern  SHORT               xoff;
extern  SHORT               ymax;
extern  SHORT               ymin;
extern  SHORT               yoff;
extern  SHORT               mode;
extern  SHORT               view_who;
extern  SHORT               no_sprites;
extern  struct  s_sprite    sprite[];
extern  SHORT               view_fight;
extern  SHORT               view_people;
extern  SHORT               ok_to_build;
extern  SHORT               build_count;
extern  SHORT               quake_count;
extern  SHORT               god_magnet;
extern  SHORT               devil_magnet;
extern  SHORT               pause;
extern  SHORT               paint_map;
extern  SHORT               surender;
extern  SHORT               cur_x;
extern  SHORT               cur_y;
extern  SHORT               not_player;
extern  SHORT               new_map;
extern  SHORT               b_rates[];
extern  SHORT               tend_x[];
extern  SHORT               tend_y[];
extern  struct  f_funny     funny[];
extern  struct  s_stats     stats[];
extern  struct  s_stats     tutorial[];
extern  USHORT              tutorial_game_mode;
extern  UBYTE               map_colour[];
extern  SHORT               baud_rate;
extern  SHORT               opposite[];
extern  USHORT              palette[];
extern  USHORT              lolpalette[];
extern  UBYTE               key_table[];
extern  SHORT               ground_in;
extern  SHORT               to_delta[];
extern  SHORT               to_offset[];
extern  SHORT               offset_vector[];
extern  SHORT               dir_sprite[];
extern  SHORT               big_city[];
extern  LONG                mana_values[];
extern  SHORT               mana_add[];
extern  SHORT               weapons_add[];
extern  SHORT               weapons_order[];
extern  SHORT               population_add[];
extern  SHORT               walk_death;
extern  SHORT               battle_add1[];
extern  SHORT               battle_add2[];
extern  SHORT               pointer;
extern  USHORT              game_mode;
extern  SHORT               in_conquest;
extern  struct  c_conquest  conquest;
extern  struct  t_text      end_ok;
extern  struct  t_text      end_cancel;
extern  struct  t_text      option_text[];
extern  UBYTE               *g_text[];
extern  struct  t_text      game_text[];
extern  struct  t_text      c_text[];
extern  UBYTE               *con_text[];
extern  struct  t_text      end_text[];
extern  SHORT               end_words[];
extern  SHORT               words[];
extern  struct  t_text      set_text[];  
extern  UBYTE               blank[];
extern  UBYTE               blank_box[];
extern  struct  t_text      serial_text[];
extern  UBYTE                *start[];
extern  UBYTE                *end[];
extern  UBYTE                *mid[];
extern  SBYTE                a_flat[];
extern  SHORT               last_fire;
extern  SHORT               last_tree;
extern  SHORT               last_rock;
extern  SHORT               p_done;
//extern  LONG                blk_data;	// Replaced by BlockGraphics

//extern  UBYTE               font_data[];	// Gone
//extern  UBYTE               icon_data[];	// Ditto.
//extern	UBYTE					blue1[]; 
//extern	UBYTE					blue2[];
//extern	UBYTE					blue3[];
//extern	UBYTE					blue4[]; 
//extern	UBYTE					blue5[]; 
//extern	UBYTE					blue6[]; 
//extern	UBYTE					blue7[]; 
//extern	UBYTE					red1[];
//extern	UBYTE					red2[];
//extern	UBYTE					red3[];
//extern	UBYTE					red4[];
//extern	UBYTE					red5[];
//extern	UBYTE					red6[];
//extern	UBYTE					red7[];
//extern	UBYTE					b_flag[];
//extern	UBYTE					r_flag[];
//extern	UBYTE					dests_array[];
extern	UBYTE					dest_array[];


//***************************
//from title extern.h
//****************************
extern  SHORT                   big_mousex;
extern  SHORT                   big_mousey;
extern  SHORT                   mouse_limit;
extern  LONG                    sprite_list[];
extern  LONG                    copper_list[];
extern  LONG                    a_sprite[];
extern  SHORT                   mmousex;
extern  SHORT                   mmousey;
extern  LONG                    spare_cl;
extern  LONG                    screen_origin;
extern  SHORT                   pal;
extern  LONG                    sprite_data_32;
extern  LONG                    current_copper;
extern  LONG                    old_copper;

extern  struct  b_building      building[];
extern  UBYTE                   **dests;
extern  UBYTE*                   the_message[];
extern  LONG                    selected;
extern  LONG                    blk_data;
extern  UBYTE                   sound_effect;
extern  SHORT                   tcmap[];
extern  LONG                    screen_pointer[];
extern  SHORT                   tempo;
extern  SHORT                   tempo_now;
extern  SHORT                   music_now;
extern  SHORT                   music;
extern  SHORT                   music_off;
extern  SHORT                   effect_off;
extern  SHORT                   effect;
extern  SHORT                   beat_two;
extern  LONG                    back_scr;
extern  LONG                    w_screen;
extern  LONG                    d_screen;
/* extern  SHORT                   no_peeps; */
extern  SHORT                   extras[];
extern  SHORT                   e_vels[];
extern  LONG                    blk_data;
extern  UBYTE                   sprite_data[];
extern  LONG                    text_line[];
extern  UBYTE                   font[];
extern  SHORT                   s_size;
extern  USHORT                  game_name[];
extern  LONG                    b_screen;
extern  LONG                    o_screen;
extern  SHORT                   oldrez;
extern  struct  w_walker        walker[];
extern  LONG                    ts1;
extern  LONG                    ts2;

extern  USHORT                  seed;
extern  SHORT                   toggle;
extern  LONG                    work_screen;
extern  UBYTE                   map_colour[];
extern  USHORT                  palette[];

extern  UBYTE                   heads[];
extern	UBYTE					res_data[];

extern  bool					is_save_load;
